title: John Martin &middot; Full stack web developer / designer
exclude: [ bower_components, node_modules, assets, gulpfile.js, bower.json, package.json, README.md ]

availability: Taking on new work from December
