exclude: [ bower_components, node_modules, assets, gulpfile.js, bower.json, package.json, README.md ]

title: John Martin &middot; Full stack web developer / designer
availability: Taking on new work from February 2016
nav: [
  {url: /, id: work, label: Work },
  {url: /about.html, id: about, label: About },
  {url: /contact.html, id: contact, label: Contact }
]
